baseUrl: https://abdus.dev
copyright: abdus!
nav:
  - text: abdus!
    href: /
    name: home
  - text: posts
    href: /posts/
  - text: projects
    href: /projects/
  - text: about me
    href: /about/
