name: build
on:
  repository_dispatch:
  push:
    branches:
      - master


jobs:
  build_pages:
    name: build pages
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          clean: false
          fetch-depth: 0

      - name: install kopkop
        run: go install github.com/abdusco/kopkop/cmd/kopkop@latest

      - name: build site
        run: PATH="$PATH:$(go env GOPATH)/bin" ./scripts/build.sh

      - name: deploy files
        run: |-
          rm -rf /apps/web/abdus.dev/static/*
          cp -r dist/. /apps/web/abdus.dev/static

      - name: deploy api
        run: |-
          cp -r api/. /apps/web/abdus.dev/api

          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          ./composer.phar install --working-dir /apps/web/abdus.dev/api --optimize-autoloader --no-dev

      - name: reload caddy
        run: |-
          caddy reload --config /etc/caddy/Caddyfile
